In [3]:
# Nama     : Reza Aditya Prabowo
# NIM      : A11.2022.14201
# Kelompok : A11.4419

# Praktek Tabular Dataset 
# =============================
# ***Universitas Dian Nuswantoro***

In [4]:
# Memasukkan Library 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
# Memasukkan Dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [6]:
# Menampilkan Dataset 
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [7]:
# Manmpilkan isi dari datasetnya
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
# Menampilkan biner dataset
print(y)

[1 0 1 ... 1 1 0]


In [9]:
# Mengencoding kategori data dari Dataset
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = ColumnTransformer([('one_hot_encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = onehotencoder.fit_transform(X)
X = X[:, 1:]

In [10]:
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


In [11]:
# Memisahkan dataset ke Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
# Melakukan Scalling dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
# Mengimport Library keras dan Packagenya
import keras
from keras.models import Sequential
from keras.layers import Dense

In [14]:
# Initialising the ANN
classifier = Sequential()

In [15]:
# Menambahkan layer pertama dari hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Menambahkan layar kedua dari hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Menambahkan layer output
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Mengcompile ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

c:\Program Files\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
# Melakukan Fitting ANN kedalam Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 849us/step - accuracy: 0.7974 - loss: 0.5475
Epoch 2/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.7968 - loss: 0.4364
Epoch 3/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 723us/step - accuracy: 0.8018 - loss: 0.4206
Epoch 4/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 814us/step - accuracy: 0.8327 - loss: 0.4050
Epoch 5/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 793us/step - accuracy: 0.8300 - loss: 0.4074
Epoch 6/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - accuracy: 0.8364 - loss: 0.4065
Epoch 7/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 831us/step - accuracy: 0.8320 - loss: 0.4081
Epoch 8/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 792us/step - accuracy: 0.8418 - loss: 0.3945
Epoch 9/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.8332 - loss: 0.4125
Epoch 10/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 843us/step - accuracy: 0.8290 - loss: 0.4159
Epoch 11/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 876us/step - accuracy: 0.8307 - loss: 0.4172
Epoch 12/100
800/80

In [17]:
# Melakukan predict dari Test Set Result
y_pred = classifier.predict(X_test)
y_pred_ = (y_pred > 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [18]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_)

In [19]:
cm

array([[1544,   51],
       [ 258,  147]], dtype=int64)

In [20]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
y_pred_

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [22]:
y_pred

array([[0.20568341],
       [0.3300047 ],
       [0.1801141 ],
       ...,
       [0.1986314 ],
       [0.15230411],
       [0.10086292]], dtype=float32)

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred_)
print("Confusion Matrix:\n", cm)

# Menghitung metrik performa
accuracy = accuracy_score(y_test, y_pred_)
precision = precision_score(y_test, y_pred_)
recall = recall_score(y_test, y_pred_)
f1 = f1_score(y_test, y_pred_)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Confusion Matrix:
 [[1544   51]
 [ 258  147]]
Accuracy: 0.8455
Precision: 0.7424242424242424
Recall: 0.362962962962963
F1 Score: 0.48756218905472637
